# Disable sudo to speed up the build
sudo: false

dist: trusty

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"

install:
  - pip install -r dev-requirements.txt

script:
  - coverage run --include "migrate_anything/*" -m pytest
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      python setup.py sdist bdist_wheel;
      twine check dist/*;
      coverage xml -i;
      mkdir coverage-reports;
      mv coverage.xml coverage-reports/coverage-python.xml;
      sonar-scanner;
    fi

deploy:
  provider: pypi
  user: "__token__"
  password: $PYPI_TOKEN
  skip_existing: true
  edge: true
  on:
    branch: master
    tags: true

addons:
  sonarcloud:
    organization: "lieturd"
    token: $SONAR_TOKEN

after_success:
  - codecov
